[package]
name = "acril"
version = "0.1.0"
edition = "2021"
description = "A microservice/actor/whatever framework."

[workspace]
members = [".", "http", "macros"]
resolver = "2"

[dependencies]
async-std = "1.12"
acril-http = { optional = true, path = "http" }
acril-macros = { path = "./macros", optional = true }
serde_urlencoded = "0.7.1"

[features]
beta = []
http = ["dep:acril-http"]
nightly = []
macros = ["dep:acril-macros"]
default = ["macros", "nightly"]

[[example]]
name = "server"
required-features = ["http"]

[[example]]
name = "client"
required-features = ["http"]

[dev-dependencies]
async-std = { version = "1.12", features = [ "attributes" ] }
tracing = "0.1.40"
tracing-subscriber = { version = "0.3.18", features = ["env-filter"] }
